export const DEFAULT_CATEGORIES = [
  { label: 'Need', icon: 'ri-shopping-cart-line', isDefault: true },
  { label: 'Want', icon: 'ri-price-tag-3-line', isDefault: true },
  { label: 'Investment', icon: 'ri-line-chart-line', isDefault: true },
];

export const REMIX_ICONS = [
  // Food & Drink
  { icon: 'ri-restaurant-line', label: 'Restaurant' },
  { icon: 'ri-cup-line', label: 'Café' },
  { icon: 'ri-cake-2-line', label: 'Bakery' },
  { icon: 'ri-goblet-line', label: 'Bar' },
  { icon: 'ri-leaf-line', label: 'Organic' },
  { icon: 'ri-apple-line', label: 'Fruit' },
  { icon: 'ri-knife-line', label: 'Kitchen' },
  // Shopping
  { icon: 'ri-shopping-cart-line', label: 'Cart' },
  { icon: 'ri-shopping-bag-line', label: 'Bag' },
  { icon: 'ri-store-2-line', label: 'Store' },
  { icon: 'ri-price-tag-3-line', label: 'Sale' },
  { icon: 'ri-handbag-line', label: 'Fashion' },
  { icon: 'ri-gift-line', label: 'Gift' },
  // Transport
  { icon: 'ri-car-line', label: 'Car' },
  { icon: 'ri-bus-line', label: 'Bus' },
  { icon: 'ri-flight-takeoff-line', label: 'Flight' },
  { icon: 'ri-taxi-line', label: 'Taxi' },
  { icon: 'ri-bike-line', label: 'Bike' },
  { icon: 'ri-train-line', label: 'Train' },
  { icon: 'ri-ship-line', label: 'Ship' },
  { icon: 'ri-e-bike-line', label: 'E-Bike' },
  // Health & Fitness
  { icon: 'ri-hospital-line', label: 'Hospital' },
  { icon: 'ri-medicine-bottle-line', label: 'Medicine' },
  { icon: 'ri-heart-pulse-line', label: 'Health' },
  { icon: 'ri-mental-health-line', label: 'Mental Health' },
  { icon: 'ri-run-line', label: 'Running' },
  { icon: 'ri-basketball-line', label: 'Sports' },
  { icon: 'ri-body-scan-line', label: 'Fitness' },
  // Entertainment
  { icon: 'ri-movie-line', label: 'Movies' },
  { icon: 'ri-music-line', label: 'Music' },
  { icon: 'ri-gamepad-line', label: 'Gaming' },
  { icon: 'ri-headphone-line', label: 'Headphones' },
  { icon: 'ri-tv-line', label: 'TV' },
  { icon: 'ri-camera-line', label: 'Camera' },
  { icon: 'ri-live-line', label: 'Streaming' },
  { icon: 'ri-ticket-line', label: 'Events' },
  // Finance & Money
  { icon: 'ri-bank-line', label: 'Bank' },
  { icon: 'ri-money-rupee-circle-line', label: 'Money' },
  { icon: 'ri-line-chart-line', label: 'Stocks' },
  { icon: 'ri-safe-2-line', label: 'Savings' },
  { icon: 'ri-hand-coin-line', label: 'Lending' },
  { icon: 'ri-exchange-line', label: 'Transfer' },
  { icon: 'ri-percent-line', label: 'Tax' },
  { icon: 'ri-coins-line', label: 'Coins' },
  // Home & Utilities
  { icon: 'ri-home-3-line', label: 'Home' },
  { icon: 'ri-lightbulb-line', label: 'Electricity' },
  { icon: 'ri-water-flash-line', label: 'Water' },
  { icon: 'ri-tools-line', label: 'Repairs' },
  { icon: 'ri-wifi-line', label: 'Internet' },
  { icon: 'ri-sofa-line', label: 'Furniture' },
  { icon: 'ri-fire-line', label: 'Gas' },
  { icon: 'ri-key-line', label: 'Rent' },
  // Education
  { icon: 'ri-book-line', label: 'Books' },
  { icon: 'ri-graduation-cap-line', label: 'Education' },
  { icon: 'ri-pen-line', label: 'Stationery' },
  { icon: 'ri-computer-line', label: 'Courses' },
  { icon: 'ri-microscope-line', label: 'Research' },
  // Travel
  { icon: 'ri-map-pin-line', label: 'Travel' },
  { icon: 'ri-hotel-line', label: 'Hotel' },
  { icon: 'ri-luggage-cart-line', label: 'Luggage' },
  { icon: 'ri-compass-line', label: 'Tourism' },
  { icon: 'ri-landscape-line', label: 'Outdoors' },
  // Tech & Subscriptions
  { icon: 'ri-smartphone-line', label: 'Phone' },
  { icon: 'ri-laptop-line', label: 'Laptop' },
  { icon: 'ri-cloud-line', label: 'Cloud' },
  { icon: 'ri-printer-line', label: 'Printer' },
  { icon: 'ri-router-line', label: 'Router' },
  // Personal Care
  { icon: 'ri-scissors-line', label: 'Haircut' },
  { icon: 'ri-palette-line', label: 'Beauty' },
  { icon: 'ri-t-shirt-line', label: 'Clothing' },
  { icon: 'ri-footprint-line', label: 'Shoes' },
  // Family & Social
  { icon: 'ri-parent-line', label: 'Family' },
  { icon: 'ri-user-heart-line', label: 'Charity' },
  { icon: 'ri-group-line', label: 'Social' },
  { icon: 'ri-home-heart-line', label: 'Household' },
  // Misc
  { icon: 'ri-seedling-line', label: 'Garden' },
  { icon: 'ri-drop-line', label: 'Water Bottle' },
  { icon: 'ri-star-line', label: 'Other' },
  { icon: 'ri-flashlight-line', label: 'Emergency' },
  { icon: 'ri-recycle-line', label: 'Eco' },
  { icon: 'ri-umbrella-line', label: 'Insurance' },
  { icon: 'ri-calendar-event-line', label: 'Events' },
  { icon: 'ri-award-line', label: 'Rewards' },
];
